/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tipedata;

import javax.swing.JOptionPane;

/**
 *
 * @author nishom
 */
public class RumusKubus extends javax.swing.JFrame {

    /**
     * Creates new form RumusKubus
     */
    public RumusKubus() {
        initComponents();
//        cmbRumus.addItem("Luas");
//        cmbRumus.addItem("Keliling");
//        cmbRumus.addItem("Volume");
//        jComboBox1.removeAllItems();
//        jComboBox1.addItem("Luas");
//        jComboBox1.addItem("Keliling");
//        jComboBox1.addItem("Volume");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_sisi = new javax.swing.JLabel();
        txtSisi = new javax.swing.JTextField();
        cmbRumus = new javax.swing.JComboBox<>();
        btnHitung = new javax.swing.JButton();
        garis = new javax.swing.JSeparator();
        lbl_hasil = new javax.swing.JLabel();
        txtHasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rumus Kubus");

        lbl_sisi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_sisi.setText("Sisi Kubus");

        txtSisi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSisi.setForeground(new java.awt.Color(0, 153, 51));

        cmbRumus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbRumus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Luas", "Keliling", "Volume" }));

        btnHitung.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        lbl_hasil.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_hasil.setForeground(new java.awt.Color(0, 153, 153));
        lbl_hasil.setText("Hasil");

        txtHasil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtHasil.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(garis)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbl_sisi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbRumus, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHitung, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                            .addComponent(txtSisi)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbl_hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHasil)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_sisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSisi, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHitung, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(cmbRumus))
                .addGap(24, 24, 24)
                .addComponent(garis, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_hasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHasil, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(455, 248));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        String s = txtSisi.getText();
        if(!s.isEmpty()){
            double hasil = 0;
            double sisi = Double.valueOf(s);
            int rumus = cmbRumus.getSelectedIndex();
            switch (rumus) {
                case 0:
                    hasil = Methods.luas_kubus(sisi);
                    break;
                case 1:
                    hasil = Methods.keliling_kubus(sisi);
                    break;
                case 2:
                    hasil = Methods.volume_kubus(sisi);
                    break;
                default:
                    break;
            }
            txtHasil.setText(""+hasil); 
        }else{
            JOptionPane.showMessageDialog(this, "Anda harus mengisi nilai sisi");
            txtSisi.requestFocus();
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RumusKubus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RumusKubus().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JComboBox<String> cmbRumus;
    private javax.swing.JSeparator garis;
    private javax.swing.JLabel lbl_hasil;
    private javax.swing.JLabel lbl_sisi;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JTextField txtSisi;
    // End of variables declaration//GEN-END:variables
}
